# Generated by Django 3.2.15 on 2022-10-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_auto_20221018_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='avilable',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
    ]
